### ISSUE TITLE
f-droid or github variant with networking, but not google services

### ISSUE THREAD

**Issue by eyecreate** [foobnix/LibreraReader#1210]
As of right now(outside the google play store), you can either use Librera on f-droid, which removes all google services as well as networking or you can use the builds on github that have networking but also google services for google drive. Is there a way one of these variants(or a new one) can have networking in order to use features like OPDS, but without adding in google services?

**Comment by foobnix** [comment]
Librera PRO variant with networking, but not google services

**Comment by foobnix** [comment]
sorry, there is no variant with networking, but no google services

**Comment by IzzySoft** [comment]
But would you consider creating such a variant? In exchange, I'd include that one with [my repo](https://apt.izzysoft.de/fdroid) then, see https://gitlab.com/IzzyOnDroid/repo/-/issues/472 for reference. Currently, with 5 "offending libs" it's just beyond the threshold of permitted "inclusion criteria violaters".

```
Offending libs:
---------------
* JUnrar (/com/github/junrar): NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Google API Client Libraries (/com/google/api/client): NonFreeNet
* Google Drive API (/com/google/api/services/drive): NonFreeDep,NonFreeNet
* Google Java API Client Services (/com/google/api/services): NonFreeNet

5 offenders.
```

It here was a variant without GDrive (which I guess is what drags in the other 3 Google libs), that would just leave JUnrar – which I do not believe is that essential (so it could ideally also be removed from that variant), but being the single left offender it would be "tolerable".

I've no idea why F-Droid removed all networking stuff altogether and consider OPDS a thing a reader should offer (well, not last out of self-interest, as I run an OPDS enabled [eBook server](https://ebooks.qumran.org/) myself), which is why I'd be totally willing making an exception to include an app already present at F-Droid, as that would be a very good reason.

Deal, @foobnix?

**Comment by foobnix** [comment]
Please check the new F-Droid build with Internet enabled in the beta.librera.mobi folder. While I believe that a F-Droid build with disabled internet access enhances security, enabling it is not a problem if you prefer :)

**Comment by eyecreate** [comment]
Is the intent that future f-droid builds will now include network?

**Comment by foobnix** [comment]
@eyecreate yes all future f-droid builds will be with internet

**Comment by IzzySoft** [comment]
@eyecreate so that solves you issue then, and inclusion with my repo would not be needed – as the new F-Droid build will have what the two of us were after?

@foobnix thanks then! Well done :smiley:

**Comment by eyecreate** [comment]
Yep, this seems to solve was I was looking for!

**Comment by softwarepagan** [comment]
I'm using the most recent FDroid build and it blocks all network connectivity, rendering features like the online catalog and dictionaries worthless. Is there a way to rectify this?
