### ISSUE TITLE
[Wiki] text selections workaround in "2 pages" PDFs 

### ISSUE THREAD

**Issue by NameLessGO** [foobnix/LibreraReader#971]
![SmartSelect_20221030_134950](https://user-images.githubusercontent.com/66227691/198890955-6c12ac62-a025-4b31-85ef-8a85ec5cefef.jpg)
Text selected top to bottom

![SmartSelect_20221030_135042](https://user-images.githubusercontent.com/66227691/198890978-91024f8f-6a3a-4a0b-accd-48ec1b927f10.jpg)
Text selected from bottom to up

Maybe is possible to make top to bottom behave like the latter, but if not (which probabbly is the case), can you put in the text selection FAQ a workaround for this problem?

Select the text bottom to up, if it doesn't select the full paragraph, change the bottom dot a little right and up to capture the whole paragraph

**Comment by pjaml** [comment]
Thanks for the workaround! I have the same issue—highlighting in two-column PDFs doesn't recognize line breaks, and highlights across both columns. Despite the workaround, I hope this could be fixed. Like you said, highlighting from the bottom up seems to ignore line breaks altogether (probably intentional):

![IMG_20221105_131519](https://user-images.githubusercontent.com/69218159/200135102-d0ec1c2d-20c5-4053-b375-69729974ae79.jpg)

**Comment by NameLessGO** [comment]
Closes with #1088, Hopefully a fix comes soon with #1086
